#!/bin/bash

function build {
    cc -O3 -o w2w w2w.c
    strip w2w
}

function install {
    sudo cp ./mouse.yaml w2w /etc/interception/
    sudo cp ./huion.yaml /etc/interception/udevmon.d/
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}
